name = "OpEngine"
uuid = "0a166e93-f540-4645-a256-0be49b1afca5"
authors = ["Joshua C. Macdonald <jmacdo16@jh.edu>"]
version = "0.1.0"

[deps]

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
